# Generated by Django 2.2.11 on 2021-04-09 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=25, unique=True)),
                ('email_verify', models.CharField(blank=True, default='not_verified', max_length=12, null=True)),
                ('mob_no', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('mob_no_verify', models.CharField(blank=True, default='not_verified', max_length=12, null=True)),
                ('password', models.CharField(max_length=30)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(default='active', max_length=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='user/photo')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('modify_date', models.DateField(blank=True, null=True)),
                ('deleted_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
