# Generated by Django 2.2.11 on 2021-04-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_auto_20210409_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
