# Generated by Django 2.2.11 on 2021-04-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_usermodel_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='f_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='l_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
