# Generated by Django 2.2.11 on 2021-04-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_auto_20210418_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='dob',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
