# Generated by Django 2.2.11 on 2021-04-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0007_auto_20210418_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='l_status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
