# Generated by Django 2.2.11 on 2021-04-18 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0008_usermodel_l_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='l_status',
            new_name='p_status',
        ),
    ]
